version: '2'
services:

  logstash:
    image: cha87de/kvmtop-datasink-logstash:latest
<<<<<<< HEAD
    environment:
    - INPUT_PORT=12345
    - OUTPUT_HOST=influxdb
    - OUTPUT_PORT=8086
    - OUTPUT_USER=admin
    - OUTPUT_PASS=secret
=======
    restart: always
>>>>>>> 0b2e427b714310d77724e929a467e6fe5057e608
    ports:
     - 12345:12345

  influxdb:
    image: influxdb:1.4-alpine
    restart: always
    stdin_open: true
    tty: true
    environment:
    - INFLUXDB_DB=kvmtop
    - INFLUXDB_HTTP_AUTH_ENABLED=true
    - INFLUXDB_ADMIN_USER=admin
    - INFLUXDB_ADMIN_PASSWORD=secret
    ports:
     - 8086:8086

  chronograf:
    image: chronograf
    restart: always
    ports:
     - 8888:8888
    command: --influxdb-url=http://influxdb:8086

     
