version: '2'
services:

  logstash:
    image: cha87de/kvmtop-datasink-logstash:latest
    environment:
    - INPUT_PORT=12345
    - OUTPUT_HOST=influxdb
    - OUTPUT_PORT=8086
    - OUTPUT_USER=admin
    - OUTPUT_PASS=secret
    restart: always
    ports:
     - 12345:12345

  influxdb:
    image: influxdb:1.4-alpine
    restart: always
    stdin_open: true
    #volumes:
    #- /opt/influxdb/:/var/lib/influxdb
    environment:
    - INFLUXDB_DB=kvmtop
    - INFLUXDB_HTTP_AUTH_ENABLED=true
    - INFLUXDB_ADMIN_USER=admin
    - INFLUXDB_ADMIN_PASSWORD=secret
    ports:
     - 8086:8086

  chronograf:
    image: chronograf
    restart: always
    #volumes:
    #- /opt/chronograf:/var/lib/chronograf
    ports:
     - 8888:8888
    command: --influxdb-url=http://influxdb:8086

  grafana-config:
    image: cha87de/kvmtop-datasink-grafana-config:latest
    restart: "no"

  grafana:
    image: grafana/grafana:latest
    ports:
    - 3000:3000/tcp
    volumes_from:
    - grafana-config
    environment:
      GF_DASHBOARDS_JSON_ENABLED: 'true'
      GF_SECURITY_ADMIN_PASSWORD: secret
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_SECRET_KEY: 1234
     
