{
 "title": "kvmtop cluster overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "content": "<center><h1>Virtual Machines</h1></center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "content": "<center><h1>Physical Machines</h1></center>"
  },
  {
   "title": "VMs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(*) FROM (SELECT last(\"cpu_cores\") FROM \"kvmtop.domains\" WHERE time >= now() - 180s GROUP BY \"UUID\" fill(none))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VM CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kvmtop.hosts",
     "query": "SELECT\n sum(\"mean_cpu_cores\") as \"vm_cpu_cores\"\nFROM \n( SELECT mean(\"cpu_cores\") as \"mean_cpu_cores\" FROM \"kvmtop\".\"autogen\".\"kvmtop.domains\" WHERE $timeFilter GROUP BY time($__interval), \"UUID\" FILL(none) )\nGROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "cpu_cores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VM Ram Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 2 },
   "format": "deckbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kvmtop.hosts",
     "query": "SELECT\n sum(\"mean_ram_total\") as \"vm_ram_total\"\nFROM \n( SELECT mean(\"ram_total\") as \"mean_ram_total\" FROM \"kvmtop\".\"autogen\".\"kvmtop.domains\" WHERE $timeFilter GROUP BY time($__interval), \"UUID\" FILL(none) )\nGROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "cpu_cores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VM Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"value\") FROM (\n  SELECT count(\"cpu_cores\") AS \"value\" FROM \"kvmtop.domains\" WHERE $timeFilter  GROUP BY  time($__interval), \"UUID\" fill(none)\n)\nGROUP BY  time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PMs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "show tag values cardinality from \"kvmtop\".\"autogen\".\"kvmtop.hosts\" with key = \"host_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PM Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n sum(\"mean_cpu_cores\") as \"cpu_cores\"\nFROM \n( SELECT mean(\"cpu_cores\") as \"mean_cpu_cores\" FROM \"kvmtop\".\"autogen\".\"kvmtop.hosts\" WHERE $timeFilter GROUP BY time($__interval), \"host_name\" FILL(none) )\nGROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PM Ram",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 2 },
   "format": "deckbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n sum(\"mean_ram_total\") as \"pm_ram_total\"\nFROM \n( SELECT mean(\"ram_Total\") as \"mean_ram_total\" FROM \"kvmtop\".\"autogen\".\"kvmtop.hosts\" WHERE $timeFilter GROUP BY time($__interval), \"host_name\" FILL(none) )\nGROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PM Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"value\") FROM (\n  SELECT count(\"cpu_cores\") AS \"value\" FROM \"kvmtop.hosts\" WHERE $timeFilter  GROUP BY  time($__interval), \"host_name\" fill(none)\n)\nGROUP BY  time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VM Cores",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kvmtop.domains",
     "query": "SELECT\n sum(\"mean_cpu_cores\") as \"vm_cpu_cores\"\nFROM \n( SELECT mean(\"cpu_cores\") as \"mean_cpu_cores\" FROM \"kvmtop\".\"autogen\".\"kvmtop.domains\" WHERE $timeFilter GROUP BY time($__interval), \"UUID\" FILL(none) )\nGROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "cpu_cores" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PM Cores",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kvmtop.domains",
     "query": "SELECT\n sum(\"mean_cpu_cores\") as \"pm_cpu_cores\"\nFROM \n( SELECT mean(\"cpu_cores\") as \"mean_cpu_cores\" FROM \"kvmtop\".\"autogen\".\"kvmtop.hosts\" WHERE $timeFilter GROUP BY time($__interval), \"host_name\" FILL(none) )\nGROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "cpu_cores" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "content": "<center><h1>VM Details</h1></center>"
  },
  {
   "title": "VMs CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kvmtop.domains",
     "query": "SELECT\n sum(\"mean_cpu_cores\") as \"vm_cpu_cores\",\n sum(\"mean_cpu_total\") / sum(\"mean_cpu_cores\") * 100 as \"vm_cpu_util\"\nFROM \n( SELECT mean(\"cpu_total\") AS \"mean_cpu_total\", mean(\"cpu_cores\") as \"mean_cpu_cores\" FROM \"kvmtop\".\"autogen\".\"kvmtop.domains\" WHERE $timeFilter GROUP BY time($__interval), \"UUID\" FILL(none) )\nGROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "cpu_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VMs Disk i/o Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n sum(\"mean_io_read_bytes\") as \"io_read_bytes\",\n sum(\"mean_io_write_bytes\") as \"io_write_bytes\"\nFROM \n( SELECT mean(\"io_read_bytes\") AS \"mean_io_read_bytes\", mean(\"io_write_bytes\") as \"mean_io_write_bytes\" FROM \"kvmtop\".\"autogen\".\"kvmtop.domains\" WHERE $timeFilter GROUP BY time($__interval), \"UUID\" FILL(none) )\nGROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VMs Disk i/o Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n sum(\"mean_io_read\") as \"io_read\",\n sum(\"mean_io_write\") as \"io_write\"\nFROM \n( SELECT mean(\"io_rchar\") AS \"mean_io_read\", mean(\"io_wchar\") as \"mean_io_write\" FROM \"kvmtop\".\"autogen\".\"kvmtop.domains\" WHERE $timeFilter GROUP BY time($__interval), \"UUID\" FILL(none) )\nGROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VMs Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n sum(\"mean_ram_used\") as \"vm_ram_used\",\n sum(\"mean_ram_total\") as \"vm_ram_total\"\nFROM \n( SELECT mean(\"ram_used\") AS \"mean_ram_used\", mean(\"ram_total\") as \"mean_ram_total\" FROM \"kvmtop\".\"autogen\".\"kvmtop.domains\" WHERE $timeFilter GROUP BY time($__interval), \"UUID\" FILL(none) )\nGROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VMs Network i/o",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n sum(\"mean_net_receivedBytes\") as \"vm_received\",\n sum(\"mean_net_transmittedBytes\") as \"vm_transmitted\"\nFROM \n( SELECT mean(\"net_receivedBytes\") AS \"mean_net_receivedBytes\", mean(\"net_transmittedBytes\") as \"mean_net_transmittedBytes\" FROM \"kvmtop\".\"autogen\".\"kvmtop.domains\" WHERE $timeFilter GROUP BY time($__interval), \"UUID\" FILL(none) )\nGROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VMs Network Issues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n sum(\"mean_net_transmittedDrop\") as \"mean_net_transmittedDrop\",\n sum(\"mean_net_transmittedErrs\") as \"mean_net_transmittedErrs\",\n sum(\"mean_net_transmittedFifo\") as \"mean_net_transmittedFifo\",\n\n sum(\"mean_net_receivedDrop\") as \"mean_net_receivedDrop\",\n sum(\"mean_net_receivedErrs\") as \"mean_net_receivedErrs\",\n sum(\"mean_net_receivedFifo\") as \"mean_net_receivedFifo\"\nFROM \n( SELECT \n  mean(\"net_transmittedDrop\") AS \"mean_net_transmittedDrop\", mean(\"net_transmittedErrs\") AS \"mean_net_transmittedErrs\", mean(\"net_transmittedFifo\") AS \"mean_net_transmittedFifo\", mean(\"net_receivedDrop\") AS \"mean_net_receivedDrop\", mean(\"net_receivedErrs\") AS \"mean_net_receivedErrs\", mean(\"net_receivedFifo\") AS \"mean_net_receivedFifo\"\n FROM \"kvmtop\".\"autogen\".\"kvmtop.domains\" WHERE $timeFilter GROUP BY time($__interval), \"UUID\" FILL(none) )\nGROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VMs CPU Steal",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kvmtop.domains",
     "query": "SELECT\n sum(\"mean_cpu_steal\")  AS \"vm_cpu_steal\"\nFROM \n( SELECT mean(\"cpu_steal\") AS \"mean_cpu_steal\" FROM \"kvmtop\".\"autogen\".\"kvmtop.domains\" WHERE $timeFilter GROUP BY time($__interval), \"UUID\" FILL(none) )\nGROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "cpu_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VMs CPU Overhead",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kvmtop.domains",
     "query": "SELECT\n sum(\"mean_cpu_other_total\")  AS \"vm_cpu_overhead\"\nFROM \n( SELECT mean(\"cpu_other_total\") AS \"mean_cpu_other_total\" FROM \"kvmtop\".\"autogen\".\"kvmtop.domains\" WHERE $timeFilter AND cpu_other_total < 100 GROUP BY time($__interval), \"UUID\" FILL(none) )\nGROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "cpu_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VMs Ram Issues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n sum(\"mean_ram_cmajflt\") as \"mean_ram_cmajflt\",\n sum(\"mean_ram_cminflt\") as \"mean_ram_cminflt\",\n sum(\"mean_ram_majflt\") as \"mean_ram_majflt\",\n sum(\"mean_ram_minflt\") as \"mean_ram_minflt\"\nFROM \n( SELECT \n  mean(\"ram_cmajflt\") AS \"mean_ram_cmajflt\", mean(\"ram_cminflt\") AS \"mean_ram_cminflt\", mean(\"ram_majflt\") AS \"mean_ram_majflt\", mean(\"ram_minflt\") AS \"mean_ram_minflt\" \n FROM \"kvmtop\".\"autogen\".\"kvmtop.domains\" WHERE $timeFilter GROUP BY time($__interval), \"UUID\" FILL(none) )\nGROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}