{
 "title": "kvmtop: virtual machine inspection",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "UUID",
    "query": "SELECT \"UUID\" FROM (SELECT last(\"cpu_cores\") FROM \"kvmtop.domains\" WHERE $timeFilter GROUP BY \"UUID\" fill(none))"
   },
   {
    "name": "host_name",
    "query": "SELECT \"host_name\" FROM (SELECT last(\"cpu_cores\") FROM \"kvmtop.domains\" WHERE $timeFilter GROUP BY \"host_name\" fill(none))"
   }
  ]
 },
 "panels": [
  {
   "title": "VMs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kvmtop.domains",
     "query": "SELECT\n  count(*)\nFROM\n(\n  SELECT last(\"cpu_cores\") AS \"cpu_cores\" FROM \"autogen\".\"kvmtop.domains\" WHERE (\"UUID\" =~ /^$UUID$/) AND (\"host_name\" =~ /^$host_name$/) AND $timeFilter GROUP BY \"UUID\" fill(none)\n) ",
     "select": [
      [
       { "params": [ "cpu_cores" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "UUID", "operator": "=~", "value": "/^$UUID$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kvmtop.domains",
     "query": "SELECT\n  sum(\"cpu_cores\") AS \"cores\"\nFROM\n(\n  SELECT mean(\"cpu_cores\") AS \"cpu_cores\" FROM \"autogen\".\"kvmtop.domains\" WHERE (\"UUID\" =~ /^$UUID$/) AND (\"host_name\" =~ /^$host_name$/) AND $timeFilter GROUP BY time($__interval), \"UUID\" fill(null)\n) GROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "cpu_cores" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "UUID", "operator": "=~", "value": "/^$UUID$/" }
     ]
    }
   ]
  },
  {
   "title": "Ram Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "deckbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kvmtop.domains",
     "query": "SELECT\n  sum(\"ram_total\") AS \"ram\"\nFROM\n(\n  SELECT mean(\"ram_total\") AS \"ram_total\" FROM \"autogen\".\"kvmtop.domains\" WHERE (\"UUID\" =~ /^$UUID$/) AND (\"host_name\" =~ /^$host_name$/) AND $timeFilter GROUP BY time($__interval), \"UUID\" fill(null)\n) GROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "ram_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "UUID", "operator": "=~", "value": "/^$UUID$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kvmtop.domains",
     "query": "SELECT\n  sum(\"disk_size_capacity\") AS \"capacity\"\nFROM\n(\n  SELECT mean(\"disk_size_capacity\") AS \"disk_size_capacity\" FROM \"autogen\".\"kvmtop.domains\" WHERE (\"UUID\" =~ /^$UUID$/) AND (\"host_name\" =~ /^$host_name$/) AND $timeFilter GROUP BY time($__interval), \"UUID\" fill(null)\n) GROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "disk_size_capacity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "UUID", "operator": "=~", "value": "/^$UUID$/" }
     ]
    }
   ]
  },
  {
   "title": "Selected VMs",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n \"UUID\", \"cpu_cores\"\nFROM\n(\n  SELECT last(\"cpu_cores\") AS \"cpu_cores\" FROM \"autogen\".\"kvmtop.domains\" WHERE (\"UUID\" =~ /^$UUID$/) AND (\"host_name\" =~ /^$host_name$/) AND $timeFilter GROUP BY \"UUID\" fill(none)\n) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "UUID" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kvmtop.domains",
     "query": "SELECT\n  sum(\"cpu_total\") AS \"cpu_total\"\nFROM\n(\n  SELECT mean(\"cpu_total\") AS \"cpu_total\" FROM \"autogen\".\"kvmtop.domains\" WHERE (\"UUID\" =~ /^$UUID$/) AND $timeFilter GROUP BY time($__interval), \"UUID\" fill(null)\n) GROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "cpu_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "UUID", "operator": "=~", "value": "/^$UUID$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "UUID" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kvmtop.domains",
     "query": "SELECT\n  sum(\"ram_total\") AS \"ram_total\",\n  sum(\"ram_used\") AS \"ram_used\"\nFROM\n(\n  SELECT mean(\"ram_total\") AS \"ram_total\",  mean(\"ram_used\") AS \"ram_used\" FROM \"autogen\".\"kvmtop.domains\" WHERE (\"UUID\" =~ /^$UUID$/) AND $timeFilter GROUP BY time($__interval), \"UUID\" fill(null)\n) GROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "cpu_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "UUID", "operator": "=~", "value": "/^$UUID$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "UUID" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kvmtop.domains",
     "query": "SELECT\n  sum(\"disk_size_capacity\") AS \"capacity\",\n  sum(\"disk_size_allocation\") AS \"allocation\"\nFROM\n(\n  SELECT mean(\"disk_size_capacity\") AS \"disk_size_capacity\", mean(\"disk_size_allocation\") AS \"disk_size_allocation\" FROM \"autogen\".\"kvmtop.domains\" WHERE (\"UUID\" =~ /^$UUID$/) AND (\"host_name\" =~ /^$host_name$/) AND $timeFilter GROUP BY time($__interval), \"UUID\" fill(null)\n) GROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "cpu_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "UUID", "operator": "=~", "value": "/^$UUID$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Profiles",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "UUID" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kvmtop.profile",
     "query": "SELECT \"UUID\", \"cpu\", \"io\", \"net\" FROM \"autogen\".\"kvmtop.profile\" WHERE (\"UUID\" =~ /^$UUID$/) AND (\"host_name\" =~ /^$host_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kvmtop.domains",
     "query": "SELECT\n  sum(\"io_read_bytes\") AS \"read_bytes\",\n  sum(\"io_write_bytes\") AS \"write_bytes\"\nFROM\n(\n  SELECT mean(\"io_read_bytes\") AS \"io_read_bytes\", mean(\"io_write_bytes\") AS \"io_write_bytes\" FROM \"autogen\".\"kvmtop.domains\" WHERE (\"UUID\" =~ /^$UUID$/) AND (\"host_name\" =~ /^$host_name$/) AND $timeFilter GROUP BY time($__interval), \"UUID\" fill(null)\n) GROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "io_read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "io_write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "UUID", "operator": "=~", "value": "/^$UUID$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kvmtop.domains",
     "query": "SELECT\n  sum(\"net_receivedBytes\") AS \"received\",\n  sum(\"net_transmittedBytes\") AS \"transmitted\"\nFROM\n(\n  SELECT mean(\"net_receivedBytes\") AS \"net_receivedBytes\", mean(\"net_transmittedBytes\") AS \"net_transmittedBytes\" FROM \"autogen\".\"kvmtop.domains\" WHERE (\"UUID\" =~ /^$UUID$/) AND (\"host_name\" =~ /^$host_name$/) AND $timeFilter GROUP BY time($__interval), \"UUID\" fill(null)\n) GROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "net_receivedBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "net_transmittedBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "UUID", "operator": "=~", "value": "/^$UUID$/" }
     ]
    }
   ]
  }
 ]
}